#!/bin/sh
xcode=/Applications/Xcode-beta.app
$xcode/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -isysroot $xcode/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk "$@" -arch arm64
